- name: "copy systemd service file"
  copy:
    src: "train-backend.service"
    dest: "/lib/systemd/system/"
    mode: 0644
  become: true
  register: systemd_file

- name: "copy nginx config"
  copy:
    src: "trains.natemara.com.conf"
    dest: "/etc/nginx/sites-available/"
    mode: 0644
  become: true
  register: "nginx_config"

- name: "Link nginx config"
  file:
    state: link
    path: "/etc/nginx/sites-enabled/trains.natemara.com"
    src: "/etc/nginx/sites-available/trains.natemara.com.conf"
    mode: 0644
  become: true

- name: "reload nginx"
  systemd:
    state: reloaded
    name: nginx
  become: true
  when: nginx_config.changed

- name: "copy backend server"
  copy:
    src: "{{ playbook_dir }}/train-schedules"
    dest: "/usr/local/bin/"
    mode: 0755
  become: true
  register: "backend_server"

- name: "restart backend server"
  systemd:
    daemon_reload: "systemd_file.changed | bool"
    state: restarted
    name: train-backend
    enabled: yes
  become: true
  when: backend_server.changed or systemd_file.changed

- name: "copy frontend files"
  copy:
    src: "{{ item }}"
    dest: "/var/www/html/"
    mode: 0644
  with_fileglob:
    - "{{ playbook_dir }}/target/deploy/train-frontend.wasm"
    - "{{ playbook_dir }}/target/deploy/train-frontend.js"
    - "{{ playbook_dir }}/frontend/static/*"
  become: true
