version: "3"
services:
  backend:
    image: rust:1.53
    volumes:
      - "./:/code"
      - "backend_target:/target"
      - "cargo_home:/cargo-home"
    environment:
      CARGO_TARGET_DIR: "/target"
      CARGO_HOME: "/cargo-home"
      API_KEY: 'x'
    working_dir: "/code/backend"
    command: cargo run

  frontend:
    build: frontend
    volumes:
      - "./:/code"
      - "frontend_target:/target"
      - "cargo_home:/cargo-home"
    environment:
      CARGO_TARGET_DIR: "/target"
      CARGO_HOME: "/cargo-home"
    working_dir: "/code/backend"
    command: trunk serve

volumes:
  backend_target: {}
  frontend_target: {}
  cargo_home: {}
