version: "3"
services:
  backend:
    image: backend-dev-server-image
    volumes:
      - "./:/code"
      - "backend_target:/target"
      - "cargo_home:/cargo-home"
    environment:
      CARGO_TARGET_DIR: "/target"
      CARGO_HOME: "/cargo-home"
    env_file: backend/.env
    working_dir: "/code/backend"
    command: cargo watch -x run

  frontend:
    depends_on:
      - backend
    image: frontend-base
    volumes:
      - "./:/code"
      - "frontend_target:/target"
      - "cargo_home:/cargo-home"
    environment:
      CARGO_TARGET_DIR: "/target"
      CARGO_HOME: "/cargo-home"
    working_dir: "/code/"
    command: "bash -c 'socat tcp-listen:8001,reuseaddr,fork tcp:localhost:8080 & trunk serve'"
    ports:
      - "8080:8001"

  prebuilt-image:
    image: lilymara:train-schedules
    env_file: backend/.env
   ports:
      - "8080:8088"

volumes:
  backend_target: {}
  frontend_target: {}
  cargo_home: {}
