[package]
name = "train-schedules"
version = "0.1.0"
authors = ["Nate Mara <nate@onesignal.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlite = "0.25.0"
actix = "0.8.3"
actix-web = { version = "1.0.7", features = ["rust-tls"] }
awc = { version = "0.2.4", features = ["rust-tls"] }
actix-rt = "0.2.4"
serde = "1.0.99"
serde_json = "1.0.40"
auto_from = "0.3.0"
chrono = "0.4.8"
train-schedules-common = { path = "../common" }
futures = "0.1.29"
