[package]
name = "train-schedules-common"
version = "0.1.0"
authors = ["Lily Mara <lilymara@fastmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.99", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
